# Generated by Django 2.2.5 on 2019-09-11 06:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0008_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThroughModel',
            new_name='Relationship',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='interests',
            new_name='bio',
        ),
    ]
