# Generated by Django 2.2.5 on 2019-09-11 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0009_auto_20190911_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('user_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('country', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
