# Generated by Django 2.2.5 on 2019-09-12 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20190912_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='num_of_tickets',
            new_name='seats',
        ),
    ]
